//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CancelOrderSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nservicebus.com", ConfigurationName="CancelOrderSvc.IWcfServiceOf_CancelOrder_ErrorCodes")]
    public interface IWcfServiceOf_CancelOrder_ErrorCodes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nservicebus.com/IWcfServiceOf_CancelOrder_ErrorCodes/Process", ReplyAction="http://nservicebus.com/IWcfServiceOf_CancelOrder_ErrorCodes/ProcessResponse")]
        Messages.ErrorCodes Process(Messages.CancelOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nservicebus.com/IWcfServiceOf_CancelOrder_ErrorCodes/Process", ReplyAction="http://nservicebus.com/IWcfServiceOf_CancelOrder_ErrorCodes/ProcessResponse")]
        System.Threading.Tasks.Task<Messages.ErrorCodes> ProcessAsync(Messages.CancelOrder request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceOf_CancelOrder_ErrorCodesChannel : Client.CancelOrderSvc.IWcfServiceOf_CancelOrder_ErrorCodes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceOf_CancelOrder_ErrorCodesClient : System.ServiceModel.ClientBase<Client.CancelOrderSvc.IWcfServiceOf_CancelOrder_ErrorCodes>, Client.CancelOrderSvc.IWcfServiceOf_CancelOrder_ErrorCodes {
        
        public WcfServiceOf_CancelOrder_ErrorCodesClient() {
        }
        
        public WcfServiceOf_CancelOrder_ErrorCodesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfServiceOf_CancelOrder_ErrorCodesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceOf_CancelOrder_ErrorCodesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceOf_CancelOrder_ErrorCodesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Messages.ErrorCodes Process(Messages.CancelOrder request) {
            return base.Channel.Process(request);
        }
        
        public System.Threading.Tasks.Task<Messages.ErrorCodes> ProcessAsync(Messages.CancelOrder request) {
            return base.Channel.ProcessAsync(request);
        }
    }
}
